// 📄 ไฟล์ attendanceLogs.js (เวอร์ชันสรุปสถิติสะสมรายคน ครบถ้วน)
const excelAttendanceLogs = [
    { employeeId: "1001", status: "มาสาย", lateMinutes: 4, remark: "สายสะสม (4 นาที)" },
    { employeeId: "1001", status: "ลาพักร้อน", lateMinutes: 0, remark: "กลับไปดูภรรยาป่วยที่ ตจว." },
    { employeeId: "1002", status: "ลาป่วย", lateMinutes: 0, remark: "ลาป่วยประจำวัน" },
    { employeeId: "1003", status: "ลากิจ", lateMinutes: 0, remark: "ไปสำนักควบคุมความประพฤติ (ลากิจรวม 2 ครั้ง)" },
    { employeeId: "1004", status: "ลากิจ", lateMinutes: 0, remark: "พ่อตาเสียชีวิต (ลากิจสะสม 4 วัน)" },
    { employeeId: "1065", status: "มาสาย", lateMinutes: 1, remark: "สาย 1 นาที | ปวดศีรษะสะสม 3 ชม." },
    { employeeId: "1084", status: "ลาพักร้อน", lateMinutes: 0, remark: "ไปต่างจังหวัด" },
    { employeeId: "1087", status: "ลากิจ", lateMinutes: 0, remark: "กิจ 2 ครั้ง (สมัครเรียนลูก/ทำใบขับขี่) | ป่วย 2 ครั้ง (ท้องเสีย/ปวดหลัง) | พักร้อน 1 ครั้ง" },
    { employeeId: "1128", status: "ลากิจ", lateMinutes: 0, remark: "เฝ้าตาป่วย รพ.สมุทรสาคร | ป่วยปวดหัว | พักร้อนไปทำธุระ" },
    { employeeId: "1142", status: "ลาป่วย", lateMinutes: 0, remark: "ติดเชื้อระบบทางเดินหายใจ รพ.วิภาราม | สายสะสม 4 ครั้ง (37 นาที)" },
    { employeeId: "1015", status: "ลากิจ", lateMinutes: 15, remark: "ลากิจ 1 ครั้ง | สาย 1 ครั้ง (15 นาที)" },
    { employeeId: "1020", status: "ลาป่วย", lateMinutes: 3, remark: "ป่วย 4 ครั้ง (รวมหมอนัดติดตามอาการ) | ล่าช้า 3 นาที" },
    { employeeId: "1025", status: "ลาป่วย", lateMinutes: 97, remark: "ป่วย 1 ครั้ง (กระเพาะปัสสาวะอักเสบ) | สายสะสม 3 ครั้ง (97 นาที)" },
    { employeeId: "1030", status: "ลาพักร้อน", lateMinutes: 0, remark: "ป่วย 0.5 วัน | พักร้อน 4 ชม. (ปฐมนิเทศโรงงานลูกชาย)" },
    { employeeId: "1035", status: "ลาป่วย", lateMinutes: 0, remark: "ลาป่วย 1 ครั้ง" },
    { employeeId: "1040", status: "ลาพักร้อน", lateMinutes: 0, remark: "ลาพักร้อน 2 ครั้ง" },
    { employeeId: "1045", status: "ลากิจ", lateMinutes: 210, remark: "ลากิจสะสม (เฝ้าพ่อป่วยวิกฤตที่ รพ. 3 ชม. 30 นาที)" },
    { employeeId: "1050", status: "ลาพักร้อน", lateMinutes: 0, remark: "ลาพักร้อน 1 ครั้ง" },
    { employeeId: "1055", status: "ลาพักร้อน", lateMinutes: 5, remark: "ลาพักร้อน 2 ครั้ง | ล่าช้า 5 นาที" },
    { employeeId: "1070", status: "ลากิจ", lateMinutes: 0, remark: "ลากิจ 1 ครั้ง" },
    { employeeId: "1075", status: "ลาป่วย", lateMinutes: 0, remark: "ลาป่วย 1 ครั้ง" },
    { employeeId: "1090", status: "ลาป่วย", lateMinutes: 0, remark: "ป่วยสะสม 7 วัน (โควิด-19 / ปวดเบ้าตา ตาแห้ง รพ.มหาชัย 2)" },
    { employeeId: "1095", status: "ลาพักร้อน", lateMinutes: 0, remark: "พักร้อน 1 วัน (ไป ตจว. นครสวรรค์)" },
    { employeeId: "1100", status: "ลาป่วย", lateMinutes: 5, remark: "ลาป่วย 1 ครั้ง (ปวดท้อง) | สายล่าช้าสะสม 2 ครั้ง (5 นาที)" },
    { employeeId: "1105", status: "มาสาย", lateMinutes: 9, remark: "ล่าช้าสะสม 3 ครั้ง (รวม 9 นาที)" },
    { employeeId: "1110", status: "ลาป่วย", lateMinutes: 0, remark: "ลาป่วย 1 ครั้ง (ไม่สบาย ไม่มีใบรับรองแพทย์)" },
    { employeeId: "1201", status: "มาสาย", lateMinutes: 75, remark: "ป่วย 1 ครั้ง (ท้องเสีย) | สายล่าช้าสะสม 5 ครั้ง (รวม 75 นาที)" }
];